apiVersion: v1
kind: Service
metadata:
  name: web-gw-dp
  namespace: nginx-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-gw-nginx   # must match the label of NGF data-plane pods
  ports:
    - name: https
      port: 443
      targetPort: 443
