apiVersion: v1
kind: Service
metadata:
  name: azurefd-sim
  namespace: edge
spec:
  type: NodePort
  selector:
    app: azurefd-sim
  ports:
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30443
